Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 242, in __init__
    self._open_camera()
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 446, in _open_camera
    self.camera.acquire()
RuntimeError: Failed to acquire camera: Device or resource busy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/Roki_2_Soccer/main_killable.py", line 68, in <module>
    vision = Vision_RPI(glob)
  File "/home/pi/Desktop/Roki_2_Soccer/Soccer/Vision/class_Vision_RPI.py", line 29, in __init__
    self.camera.start(exposure = self.TH['exposure'], gain = self.TH['gain'], frame_duration_us = CAMERA_FRAME_DURATION_US)
  File "/home/pi/Desktop/Roki_2_Soccer/Soccer/Vision/camera.py", line 34, in start
    self.picam2 = Picamera2(camera_num=0)
  File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 254, in __init__
    raise RuntimeError("Camera __init__ sequence did not complete.")
RuntimeError: Camera __init__ sequence did not complete.
